# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_mynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynote',
            name='textfield',
            field=models.CharField(default='', max_length=10),
        ),
    ]
