# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_mynote_textfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mynote',
            name='textfield',
        ),
    ]
