# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_mynote_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceID', models.CharField(max_length=10)),
                ('CustomerProduct', models.CharField(max_length=50)),
                ('NpPara', models.IntegerField(null=True)),
                ('InputDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ProductType', models.CharField(max_length=8, null=True)),
            ],
        ),
    ]
