# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170618_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='Tester',
            field=models.CharField(default='', max_length=20),
        ),
    ]
