from django.conf.urls import url
#from .views import ThingList, ThingCreate, ThingDetail, ThingUpdate, ThingDelete
from . import views

urlpatterns = [
    url(r'^javatutor/demo1/$', views.javatutor_demo1, name='demo1'),
    url(r'^javatutor/demo2/$', views.javatutor_demo2, name='demo2'),
    url(r'^javatutor/demo3/$', views.javatutor_demo3, name='demo3'),
    url(r'^javatutor/demo4/$', views.javatutor_demo4, name='demo4'),
    url(r'^javatutor/demo5/$', views.javatutor_demo5, name='demo5'),
    url(r'^javatutor/demo21/$', views.javatutor_demo21, name='demo21'),
    url(r'^javatutor/demo22/$', views.javatutor_demo22, name='demo22'),
    url(r'^javatutor/demo23/$', views.javatutor_demo23, name='demo23'),
    url(r'^javatutor/demo24/$', views.javatutor_demo24, name='demo24'),
    url(r'^javatutor/demo25/$', views.javatutor_demo25, name='demo25'),
    url(r'^javatutor/demo26/$', views.javatutor_demo26, name='demo26'),
    url(r'^javatutor/demo27/$', views.javatutor_demo27, name='demo27'),
    url(r'^javatutor/demo28/$', views.javatutor_demo28, name='demo28'),
    url(r'^javatutor/demo31/$', views.javatutor_demo31, name='demo31'),
    url(r'^javatutor/demo32/$', views.javatutor_demo32, name='demo32'),
    url(r'^javatutor/demo33/$', views.javatutor_demo33, name='demo33'),
    url(r'^javatutor/demo34/$', views.javatutor_demo34, name='demo34'),
    url(r'^javatutor/demo41/$', views.javatutor_demo41, name='demo41'),
    url(r'^javatutor/demo42/$', views.javatutor_demo42, name='demo42'),
    url(r'^javatutor/demo43/$', views.javatutor_demo43, name='demo43'),
    url(r'^javatutor/demo44/$', views.javatutor_demo44, name='demo44'),
    url(r'^javatutor/demo45/$', views.javatutor_demo45, name='demo45'),
    url(r'^javatutor/demo46/$', views.javatutor_demo46, name='demo46'),
    url(r'^javatutor/demo47/$', views.javatutor_demo47, name='demo47'),
    url(r'^javatutor/demo51/$', views.javatutor_demo51, name='demo51'),
    url(r'^javatutor/demo52/$', views.javatutor_demo52, name='demo52'),
    url(r'^javatutor/demo53/$', views.javatutor_demo53, name='demo53'),
    url(r'^javatutor/demo54/$', views.javatutor_demo54, name='demo54'),
    url(r'^javatutor/demo55/$', views.javatutor_demo55, name='demo55'),
    url(r'^javatutor/demo56/$', views.javatutor_demo56, name='demo56'),
    url(r'^javatutor/demo57/$', views.javatutor_demo57, name='demo57'),
    url(r'^javatutor/demo61/$', views.javatutor_demo61, name='demo61'),
    url(r'^javatutor/demo62/$', views.javatutor_demo62, name='demo62'),

    url(r'^ajx/mygetview', views.mygetview, name='mygetview'),
    url(r'^ajx/mypostview', views.mypostview, name='mypostview'),
    url(r'^ajx/myajaxview', views.myajaxview, name='myajaxview'),
    url(r'^ajx/myajaxformview', views.myajaxformview, name='myajaxformview'),

]